//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DoHide.rc
//
#define IDS_LANG                        1
#define IDS_UNABLE_LOAD_LANGUAGE_DLL    1
#define IDS_LANG1                       2
#define IDS_DOHIDE_TITLE                2
#define IDS_LANG2                       3
#define IDS_HOTKEY1                     11
#define IDS_HOTKEY2                     12
#define IDS_HOTKEY3                     13
#define IDS_HOTKEY4                     14
#define IDS_HOTKEY5                     15
#define IDS_HOTKEY6                     16
#define IDS_HOTKEY7                     17
#define IDS_HOTKEY8                     18
#define IDS_HOTKEY9                     19
#define IDS_HOTKEY10                    20
#define IDS_HOTKEY11                    21
#define IDS_HOTKEY12                    22
#define IDS_HOTKEY13                    23
#define IDS_HOTKEY14                    24
#define IDS_HOTKEY15                    25
#define IDS_HOTKEY16                    26
#define IDS_HOTKEY17                    27
#define IDS_HOTKEY18                    28
#define IDS_HOTKEY19                    29
#define IDS_HOTKEY20                    30
#define IDS_HOTKEY21                    31
#define IDS_HOTKEY22                    32
#define IDS_HOTKEY23                    33
#define IDS_HOTKEY24                    34
#define IDS_HOTKEY25                    35
#define IDS_HOTKEY26                    36
#define IDS_HOTKEY27                    37
#define IDS_HOTKEY28                    38
#define IDS_HOTKEY29                    39
#define IDS_HOTKEY30                    40
#define IDS_HOTKEY31                    41
#define IDS_HOTKEY32                    42
#define IDS_HOTKEY33                    43
#define IDS_HOTKEY34                    44
#define IDS_HOTKEY35                    45
#define IDS_PROPERTIES1                 100
#define IDS_PROPERTIES2                 101
#define IDD_DIALOG1                     101
#define IDS_PROPERTIES3                 102
#define IDD_HIDE_BY_RUN                 102
#define IDS_PROPERTIES4                 103
#define IDR_POPUPMENU                   103
#define IDS_PROPERTIES5                 104
#define IDR_POPUPMENU1                  104
#define IDS_PROPERTIES6                 105
#define IDR_POPUPMENU2                  105
#define IDD_HOTKEY_DIALOG               106
#define IDD_LOCK_DIALOG                 107
#define IDD_OPTIONS_DIALOG              108
#define IDD_PROGRAMS_DIALOG             109
#define IDS_HEADER1                     110
#define IDD_REGISTER_DIALOG             110
#define IDS_HEADER2                     111
#define IDD_TRAYNOT_PROGRAMS            111
#define IDS_HEADER3                     112
#define IDD_WELCOME_DIALOG              112
#define IDS_HIDDEN_WINDOWS              113
#define IDS_DESKTOP_ICONS               114
#define IDS_NO_WINDOW                   115
#define IDS_REMOVE                      116
#define IDI_CPU                         116
#define IDS_RUN_FROM_TRAY               117
#define IDS_EXPIRED                     118
#define IDS_DESKTOP                     119
#define IDS_RECENT                      120
#define IDS_IEXPLORER                   121
#define IDS_DIALUP                      122
#define IDD_MAIN_DIALOG                 123
#define IDS_TRANSLATED_BY               124
#define IDS_OPFD_1                      125
#define IDS_OPFD_2                      126
#define IDS_OPFD_3                      127
#define IDD_PASSWORD_DIALOG             128
#define IDS_CONTROL_PANEL               129
#define IDS_PRINTERS                    130
#define IDS_PASSWORD_VERIFY             131
#define IDS_CPU				            132
#define IDS_LANGUAGE                    200
#define IDS_LANGUAGE_ID                 201
#define IDS_LANGUAGE_HELP               202
#define ID_HIDE_BY_RUN                  221
#define ID_ADD_TO_TRAY                  222
#define ID_OPTIONS_TAB                  223
#define ID_HOTKEY_TAB                   224
#define ID_HIDEBYRUN_TAB                225
#define ID_PROGRAM_TAB                  226
#define IDB_LOGO                        300
#define IDB_LOGO1                       301
#define IDC_HLINK                       302
#define IDC_TARGET                      303
#define IDI_DOHIDE                      304
#define IDI_TARGET1                     305
#define IDI_TARGET                      306
#define IDI_DIAL                        308
#define IDI_IEXPLORER                   309
#define IDI_PROGRAM                     310
#define IDI_LAMP                        311
#define IDI_ICON2                       312
#define IDI_LOCK                        313
#define IDI_HOTKEY                      314
#define IDI_OPTIONS                     315
#define IDI_REGISTER                    316
#define IDI_DESKTOP                     317
#define IDI_RECENT                      318
#define IDI_CONTROL_PANEL               319
#define IDI_PRINTERS                    320
#define IDI_PROTECTED                   321
#define IDC_LISTBOX                     1000
#define IDC_CLOSE                       1001
#define IDC_HIDE                        1002
#define IDC_EDIT22                      1002
#define IDC_EDIT23                      1003
#define ID_BUTTON20                     1004
#define ID_ABOUT                        1005
#define IDD_CONFIG                      1006
#define IDC_TAB1                        1007
#define IDC_CONFIG                      1008
#define IDC_EDIT                        1010
#define IDC_CHECK1                      1011
#define IDC_CHECK14                     1012
#define ID_RESTORE                      1027
#define IDC_CHECK2                      1028
#define IDC_CHECK9                      1029
#define IDC_CHECK21                     1029
#define IDC_CHECK3                      1030
#define IDC_CHECK30                     1030
#define IDC_CHECK4                      1031
#define IDC_CHECK5                      1032
#define IDC_CHECK29                     1032
#define IDC_CHECK6                      1033
#define IDC_CHECK10                     1033
#define IDC_CHECK25                     1033
#define ID_SCREEN_SAVER                 1034
#define IDC_CHECK11                     1034
#define IDC_CHECK26                     1034
#define ID_LOGOFF                       1035
#define IDC_CHECK12                     1035
#define IDC_CHECK27                     1035
#define ID_SHUTDOWN                     1036
#define IDC_CHECK16                     1036
#define ID_REBOOT                       1037
#define IDC_CHECK7                      1038
#define IDC_CHECK8                      1039
#define IDC_BUTTON1                     1040
#define IDC_CHECK13                     1040
#define ID_KILL_PROCESS                 1041
#define IDC_CHECK15                     1041
#define IDC_BTN_DOWN                    1041
#define IDC_NONE                        1043
#define IDC_NONE1                       1044
#define IDC_NONE2                       1045
#define IDC_TIME                        1046
#define IDC_RESPONSE                    1047
#define IDC_HYPERLINK                   1048
#define IDC_HYPERLINK2                  1049
#define IDC_LIST2                       1051
#define IDC_LIST1                       1052
#define IDC_BUTTON2                     1053
#define IDC_BUTTON3                     1054
#define IDC_BUTTON4                     1055
#define IDC_EDIT1                       1056
#define IDC_EDIT21                      1056
#define IDC_EDIT2                       1057
#define IDC_EDIT20                      1057
#define IDC_CHECK20                     1060
#define IDC_CHECK22                     1061
#define IDC_CHECK23                     1062
#define IDC_CHECK24                     1063
#define IDC_BUTTON20                    1064
#define IDC_BITMAP                      1065
#define IDC_CHECK28                     1065
#define IDC_BITMAP1                     1066
#define IDC_EDIT24                      1066
#define IDC_SLIDER1                     1067
#define IDC_EDIT3                       1068
#define IDC_EDIT4                       1069
#define IDC_PROGRAM_ICON                1069
#define ID_RUN_PROGRAM                  1070
#define ID_EDIT_PROGRAM                 1071
#define IDC_EDIT25                      1071
#define ID_ADD_PROGRAM                  1072
#define IDC_CHECK32                     1072
#define ID_DELETE_PROGRAM               1073
#define IDC_DAYSLEFT                    1077
#define ID_REGISTER                     1078
#define IDC_DAYSLEFT2                   1078
#define IDC_CHECK31                     1079
#define IDC_TARGET_BITMAP               1080
#define IDC_RADIO1                      1081
#define IDC_RADIO2                      1082
#define IDC_RADIO3                      1083
#define IDC_RADIO4                      1084
#define IDC_BTN_UP                      1085
#define IDC_BTN_ADD                     1086
#define IDC_BTN_EDIT                    1087
#define IDC_BTN_REMOVE                  1088
#define IDC_LANG_COMBO                  1090
#define IDC_CHECK33                     1091
#define IDC_CHECK34                     1092
#define IDC_PASSWORD                    1093
#define IDC_CHECK35                     1094
#define IDC_CHECK17                     1095
#define IDC_CHECK18                     1096
#define IDC_HYPERLINK5                  1097
#define IDC_HYPERLINK6                  1098
#define IDC_CHECK19                     1099
#define IDC_HOTKEY1                     2012
#define IDC_HOTKEY2                     2013
#define IDC_HOTKEY3                     2014
#define IDC_HOTKEY4                     2015
#define IDC_HOTKEY5                     2016
#define IDC_HOTKEY6                     2017
#define IDC_HOTKEY7                     2018
#define IDC_HOTKEY8                     2019
#define IDC_HOTKEY9                     2020
#define IDC_HOTKEY10                    2021
#define IDC_HOTKEY11                    2022
#define IDC_HOTKEY12                    2023
#define IDC_HOTKEY13                    2024
#define IDC_HOTKEY14                    2025
#define IDC_HOTKEY15                    2026
#define IDC_HOTKEY16                    2027
#define IDC_HOTKEY17                    2028
#define IDC_HOTKEY18                    2029
#define IDC_HOTKEY19                    2030
#define IDC_HOTKEY20                    2031
#define IDC_HOTKEY21                    2032
#define IDC_HOTKEY22                    2033
#define IDC_HOTKEY23                    2034
#define IDC_HOTKEY24                    2035
#define IDC_HOTKEY25                    2036
#define IDC_HOTKEY26                    2037
#define IDC_HOTKEY27                    2038
#define IDC_HOTKEY28                    2039
#define IDC_HOTKEY29                    2040
#define IDC_HOTKEY30                    2041
#define IDC_HOTKEY31                    2042
#define IDC_HOTKEY32                    2043
#define IDC_HOTKEY33                    2044
#define IDC_HOTKEY34                    2045
#define IDC_HOTKEY35                    2046
#define IDC_HOTKEY36                    2047
#define IDC_HOTKEY37                    2048
#define IDC_HOTKEY38                    2049
#define IDC_HOTKEY39                    2050
#define IDC_HOTKEY40                    2051
#define IDC_HOTKEY41                    2052
#define IDC_HOTKEY42                    2053
#define IDC_HOTKEY43                    2054
#define IDC_HOTKEY44                    2055
#define IDC_HOTKEY45                    2056
#define IDC_HOTKEY46                    2057
#define IDC_HOTKEY47                    2058
#define IDC_HOTKEY48                    2059
#define IDC_HOTKEY49                    2060
#define IDC_HOTKEY50                    2061
#define IDC_TRANSLATED                  2062
#define IDC_PASSWORD1                   3001
#define IDC_PASSWORD2                   3002
#define IDC_CHECK100                    3003
#define IDC_CHECK101                    3004
#define IDC_CHECK102                    3005
#define IDC_CHECK103                    3006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
